"""create_targets_table

Revision ID: a4ddbabe47cd
Revises:
Create Date: 2026-06-17 15:09:59.174870

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4ddbabe47cd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "targets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("mac_address", sa.String(length=17), nullable=True),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_targets_id"), "targets", ["id"], unique=False)
    op.create_index(
        op.f("ix_targets_ip_address"), "targets", ["ip_address"], unique=False
    )
    op.create_table(
        "scanjobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scanjobs_id"), "scanjobs", ["id"], unique=False)
    op.create_index(op.f("ix_scanjobs_status"), "scanjobs", ["status"], unique=False)
    op.create_table(
        "scanresults",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("raw_output", sa.Text(), nullable=True),
        sa.Column("parsed_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["scanjobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    op.create_index(op.f("ix_scanresults_id"), "scanresults", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scanresults_id"), table_name="scanresults")
    op.drop_table("scanresults")
    op.drop_index(op.f("ix_scanjobs_status"), table_name="scanjobs")
    op.drop_index(op.f("ix_scanjobs_id"), table_name="scanjobs")
    op.drop_table("scanjobs")
    op.drop_index(op.f("ix_targets_ip_address"), table_name="targets")
    op.drop_index(op.f("ix_targets_id"), table_name="targets")
    op.drop_table("targets")
    # ### end Alembic commands ###
